[0m[[0minfo[0m] [0mRunning com.example.Hello [0m
[0m[[0mdebug[0m] [0mWaiting for threads to exit or System.exit to be called.[0m
[0m[[0mdebug[0m] [0mWaiting for thread run-main-0 to terminate.[0m
[0m[[0mdebug[0m] [0m  Classpath:[0m
[0m[[0mdebug[0m] [0m	/home/simar/slickDemo/target/scala-2.12/classes[0m
[0m[[0mdebug[0m] [0m	/home/simar/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.1.jar[0m
[0m[[0mdebug[0m] [0m	/home/simar/.ivy2/cache/com.typesafe.slick/slick_2.12/bundles/slick_2.12-3.2.0.jar[0m
[0m[[0mdebug[0m] [0m	/home/simar/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar[0m
[0m[[0mdebug[0m] [0m	/home/simar/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar[0m
[0m[[0mdebug[0m] [0m	/home/simar/.ivy2/cache/com.typesafe.slick/slick-hikaricp_2.12/bundles/slick-hikaricp_2.12-3.2.0.jar[0m
[0m[[0mdebug[0m] [0m	/home/simar/.ivy2/cache/com.zaxxer/HikariCP/bundles/HikariCP-2.5.1.jar[0m
[0m[[0mdebug[0m] [0m	/home/simar/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.21.jar[0m
[0m[[0mdebug[0m] [0m	/home/simar/.ivy2/cache/org.postgresql/postgresql/bundles/postgresql-9.4.1212.jar[0m
[0m[[0mdebug[0m] [0m	/home/simar/.ivy2/cache/mysql/mysql-connector-java/jars/mysql-connector-java-5.1.34.jar[0m
[0m[[31merror[0m] [0m(run-main-0) com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '4' for key 'PRIMARY'[0m
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '4' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.Util.getInstance(Util.java:360)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:971)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2141)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2077)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2062)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.$anonfun$run$11(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$Lambda$1674/1047646548.apply(Unknown Source)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:372)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:367)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:434)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:502)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:508)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:31)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:534)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:534)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction$$Lambda$1764/2008651850.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:534)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[0m[[0mdebug[0m] [0m	Thread run-main-0 exited.[0m
[0m[[0mdebug[0m] [0mInterrupting remaining threads (should be all daemons).[0m
[0m[[0mdebug[0m] [0mInterrupting thread Abandoned connection cleanup thread[0m
[0m[[0mdebug[0m] [0m	Interrupted Abandoned connection cleanup thread[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-2[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-2[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-5[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-5[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-2[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-2[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-4[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-4[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-2[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-2[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-1[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-1[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-5[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-5[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-8[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-8[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-1[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-1[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-4[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-4[0m
[0m[[0mdebug[0m] [0mInterrupting thread scala-execution-context-global-44[0m
[0m[[0mdebug[0m] [0m	Interrupted scala-execution-context-global-44[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-6[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-6[0m
[0m[[0mdebug[0m] [0mInterrupting thread scala-execution-context-global-45[0m
[0m[[0mdebug[0m] [0m	Interrupted scala-execution-context-global-45[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-3[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-3[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-7[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-7[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-7[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-7[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-1[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-1[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-3[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-3[0m
[0m[[0mdebug[0m] [0mInterrupting thread myMySqlDB-6[0m
[0m[[0mdebug[0m] [0m	Interrupted myMySqlDB-6[0m
[0m[[0mdebug[0m] [0mSandboxed run complete..[0m
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2128)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2128)
	at scala.Option.foreach(Option.scala:236)
	at sbt.BuildCommon$class.toError(Defaults.scala:2128)
	at sbt.Defaults$.toError(Defaults.scala:39)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$46$$anonfun$apply$47.apply(Defaults.scala:769)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$46$$anonfun$apply$47.apply(Defaults.scala:767)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[0m[[31merror[0m] [0m(compile:[31mrun[0m) Nonzero exit code: 1[0m
